# Dict with uid's as key and a nested dict with configuration variables
general:
  runtime: 1800  # seconds
  number_of_samples: &number_of_samples 4250
  analogue_offset: &analogue_offset -0.48  # in V and not adc!
  sample_time_ns: &sample_time_ns 4

pico_3000:
  channels: 4
  channel_coupling: "DC"
  channel_range: "500MV"
  analogue_offset: *analogue_offset
  #TODO: Change the value below to what you found with the PicoScope Software! 
  trigger_threshold: 0000  # The trigger voltage threshold in mV. Make sure not to exceed channel_range!
  trigger_channel: "A"  # Channel name in the PicoScope. Valid values are 'A', 'B', 'C' or 'D'
  pre_trigger_samples: &pre_trigger_samples 500
  post_trigger_samples: 3750
  total_samples: *number_of_samples  # sanity check for above two values
  timebase: 2  # see PicoScope manual or keep at 2 for maximum resolution (4ns sample time)
  time_interval_ns: *sample_time_ns # This is a sanity check and has to correlate to timebase (see PicoScope manual)
  number_of_memory_segments: 750

calculate_decay_time:
  sample_time_ns: *sample_time_ns
  analogue_offset: *analogue_offset
  number_of_samples: *number_of_samples
  pre_trigger_samples: *pre_trigger_samples
  #TODO: Change the values below to the stretch values calculated with the spectrum.txt
  chA_scaling: 1  # Scaling factor to match trigger thresholds for each panel
  chB_scaling: 1  # Scaling factor to match trigger thresholds for each panel
  chC_scaling: 1  # Scaling factor to match trigger thresholds for each panel
  chD_scaling: 1  # Scaling factor to match trigger thresholds for each panel
  #TODO: Change the values below to what you found from the peak height spectrum.
  peak_minimal_prominence_initial: 0000  # in mV, minimal expected peak height for a muon. Has to be higher than noise peaks to not cause havoc!
  peak_minimal_prominence_secondary: 0000  # in mV, minnimal expected peak height for an electron/positron. Has to be higher than noise peaks to not cause havoc!
  peak_minimal_distance: 10  # minimal distance between two peaks in number of samples (10 samples -> 40ns)
  peak_minimal_width: 10  # in number of samples (10 samples -> 40ns)
  trigger_position_tolerance: 20
  signatures:
    #    chA  chB  chC  chD
    - - ["+", "+", "-", "-"]  # 1st start signature (muon catched in copper)
      - ["0", "+", "-", "-"]  # 1st stop signature (decay positron in upwards direction)
      
    - - ["+", "+", "-", "-"]  # 2nd start signature (muon catched in copper)
      - ["-", "-", "+", "0"]  # 2nd stop signature (decay positron in downwards direction)

    - - ["+", "+", "+", "+"]  # 3rd start signature (muon catched in lead/concrete under the detectors)
      - ["0", "0", "0", "+"]  # 3rd stop signature (decay positron in upwards direction)

save_to_txt:
  filename: "lifetime"
  header_alias:
    'counter': 'event id'
    'timestamp': 'time of event (UTC)'
    'deadtime': 'dead time'
    'decay_time': 'decay time (ns)'
    '1st_chA_h': '1st chA height'
    '1st_chB_h': '1st chB height'
    '1st_chC_h': '1st chC height'
    '1st_chD_h': '1st chD height'
    '1st_chA_p': '1st chA position'
    '1st_chB_p': '1st chB position'
    '1st_chC_p': '1st chC position'
    '1st_chD_p': '1st chD position'
    '1st_chA_int': '1st chA integral'
    '1st_chB_int': '1st chB integral'
    '1st_chC_int': '1st chC integral' 
    '1st_chD_int': '1st chD integral'
    '2nd_chA_h': '2nd chA height'
    '2nd_chB_h': '2nd chB height'
    '2nd_chC_h': '2nd chC height'
    '2nd_chD_h': '2nd chD height'
    '2nd_chA_p': '2nd chA position'
    '2nd_chB_p': '2nd chB position'
    '2nd_chC_p': '2nd chC position'
    '2nd_chD_p': '2nd chD position'
    '2nd_chA_int': '2nd chA integral'
    '2nd_chB_int': '2nd chB integral'
    '2nd_chC_int': '2nd chC integral' 
    '2nd_chD_int': '2nd chD integral'
  
save_parquet:
  filename: "muon_decay"

plot_graph:
  sample_time_ns: *sample_time_ns
  title: "Muon decay waveform"
