filename: "spin_top"
header_alias:
    'counter': 'event id'
    'timestamp': 'time of event (UTC)'
    'deadtime': 'dead time'
    'decay_time': 'decay time (ns)'
    '1st_chA_h': '1st chA height'
    '1st_chB_h': '1st chB height'
    '1st_chC_h': '1st chC height'
    '1st_chD_h': '1st chD height'
    '1st_chA_p': '1st chA position'
    '1st_chB_p': '1st chB position'
    '1st_chC_p': '1st chC position'
    '1st_chD_p': '1st chD position'
    '1st_chA_int': '1st chA integral'
    '1st_chB_int': '1st chB integral'
    '1st_chC_int': '1st chC integral' 
    '1st_chD_int': '1st chD integral'
    '2nd_chA_h': '2nd chA height'
    '2nd_chB_h': '2nd chB height'
    '2nd_chC_h': '2nd chC height'
    '2nd_chD_h': '2nd chD height'
    '2nd_chA_p': '2nd chA position'
    '2nd_chB_p': '2nd chB position'
    '2nd_chC_p': '2nd chC position'
    '2nd_chD_p': '2nd chD position'
    '2nd_chA_int': '2nd chA integral'
    '2nd_chB_int': '2nd chB integral'
    '2nd_chC_int': '2nd chC integral' 
    '2nd_chD_int': '2nd chD integral'
