# Dictionaries for muon life time measurement
#
general:
  runtime: 10
  number_of_samples: &number_of_samples 4250
  analogue_offset: &analogue_offset -0.48  # in V and not adc!
  sample_time_ns: &sample_time_ns 4
  pre_trigger_samples: &pre_trigger_samples 500

# Dict for simulation_source.py
simulation_source:
  sample_time_ns: *sample_time_ns
  number_of_samples: *number_of_samples
  pre_trigger_samples: *pre_trigger_samples
  analogue_offset: *analogue_offset
  eventcount: 10000000
  sleeptime: 0.003
  random: true

calculate_decay_time:
  analogue_offset: *analogue_offset
  number_of_samples: *number_of_samples
  sample_time_ns: *sample_time_ns
  pre_trigger_samples: *pre_trigger_samples
  #TODO: adjust the scaling factors to values obtained from spectrum measurements
  chA_scaling: 1.00  # Scaling factor to match trigger thresholds for each panel
  chB_scaling: 1.00  # Scaling factor to match trigger thresholds for each panel
  chC_scaling: 1.00  # Scaling factor to match trigger thresholds for each panel
  chD_scaling: 1.00  # Scaling factor to match trigger thresholds for each panel
  #TODO: Change the values below to what you found from the peak height spectrum.
  peak_minimal_prominence_initial: 90  # in mV, minimal expected peak height for a muon. Has to be higher than noise peaks to not cause havoc!
  peak_minimal_prominence_secondary: 35  # in mV, minnimal expected peak height for an electron/positron. Has to be higher than noise peaks to not cause havoc!
  peak_minimal_distance: 10  # minimal distance between two peaks in number of samples (10 samples -> 40ns)
  peak_minimal_width: 10  # in number of samples (10 samples -> 40ns)
  trigger_position_tolerance: 20
  signatures:
    #    chA  chB  chC  chD
    - - ["+", "+", "-", "-"]  # 1st start signature (muon stopped in copper)
      - ["0", "+", "-", "-"]  # 1st stop signature (decay positron in upwards direction)
      
    - - ["+", "+", "-", "-"]  # 2nd start signature (muon stopped in copper)
      - ["-", "-", "+", "0"]  # 2nd stop signature (decay positron in downwards direction)

    - - ["+", "+", "+", "+"]  # 3rd start signature (muon stopped in lead/concrete under the detectors)
      - ["0", "0", "0", "+"]  # 3rd stop signature (decay positron in upwards direction)

save_to_txt:
  filename: "simulated_lifetimes"
  header_alias:
    'counter': 'event id'
    'timestamp': 'time of event (UTC)'
    'deadtime': 'dead time'
    'decay_time': 'decay time (ns)'
    '1st_chA_h': '1st chA height'
    '1st_chB_h': '1st chB height'
    '1st_chC_h': '1st chC height'
    '1st_chD_h': '1st chD height'
    '1st_chA_p': '1st chA position'
    '1st_chB_p': '1st chB position'
    '1st_chC_p': '1st chC position'
    '1st_chD_p': '1st chD position'
    '1st_chA_int': '1st chA integral'
    '1st_chB_int': '1st chB integral'
    '1st_chC_int': '1st chC integral' 
    '1st_chD_int': '1st chD integral'
    '2nd_chA_h': '2nd chA height'
    '2nd_chB_h': '2nd chB height'
    '2nd_chC_h': '2nd chC height'
    '2nd_chD_h': '2nd chD height'
    '2nd_chA_p': '2nd chA position'
    '2nd_chB_p': '2nd chB position'
    '2nd_chC_p': '2nd chC position'
    '2nd_chD_p': '2nd chD position'
    '2nd_chA_int': '2nd chA integral'
    '2nd_chB_int': '2nd chB integral'
    '2nd_chC_int': '2nd chC integral' 
    '2nd_chD_int': '2nd chD integral'
  
save_parquet:
  filename: "simulated_data"

plot_graph:
  title: "Waveform Double Pulses"
  min_sleeptime: 0.5                # time to wait between graphics updates
  sample_time_ns: *sample_time_ns   # sampling interval 
  channel_range: 500                # channel range in mV
  analogue_offset: *analogue_offset # analogue offset in V
  number_of_samples: *number_of_samples
  pre_trigger_samples: *pre_trigger_samples

read_from_buffer:
  dummy: none   # need an empty dictionay

